blog/urls.py
from sre_constants import IN
from django.contrib import admin
from homepage.views import IndexView,AboutView
from django.urls import include, path

from posts.views import CategoriaCreateView, CategoriaListView, UserCreateView, lista_usuarios

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),

    path('user/', UserCreateView.as_view(), name='user'),
    path('listado_usuarios/', lista_usuarios, name='list_users'),

    path('categoria/', CategoriaCreateView.as_view(), name='categoria'),  
    path('listado_categoria/', CategoriaListView.as_view(), name='list_categoria'),  

    path('about/', AboutView.as_view(), name='about'),
    path('post/', include(('posts.urls'), namespace='post'))    # namespace funciona si se define el nobmre de app, en el archivo urls.py de la App
]

posts/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'post'

urlpatterns = [
    path('', PostListView.as_view(), name="list"),
    
    path('create/', PostCreateView.as_view(), name="create"),

    path('<int:pk>/', PostDetailView.as_view(), name="detail"),

    path('<int:pk>/update', PostUpdateView.as_view(), name="update"),
    
    path('<int:pk>/delete', PostDeleteView.as_view(), name="delete"),
]

homepage/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(max_length=255)
    #content_image = models.ImageField()
    publish_date = models.DateTimeField(auto_now_add=True) # Cuando se publica se agrega automaticamente la fecha actual
    last_update = models.DateTimeField(auto_now=True)
    # Vincular tablas

    def __str__(self):
        return self.title
class Usuario(models.Model):
    nombre = models.CharField(max_length=20)
    apellido = models.CharField(max_length=30)
    email = models.EmailField(max_length=254)
    
    def __str__(self):
        return f'{self.nombre} {self.apellido}'
class Categoria(models.Model):
    nombre = models.CharField(max_length=20)
    activo = models.BooleanField()
    
    def __str__(self):
        return f'{self.nombre}'

posts/forms.py
from django import forms
from .models import Categoria, Post, Usuario

class PostForm(forms.ModelForm):
     class Meta:
        model = Post
        fields = ('title', 'content',)
        widgets = {                                                        # Me permite utilizar bootstrap para el form
           'title': forms.TextInput(attrs={'class':'form-control'}),
           'content': forms.Textarea(attrs={'class':'form-control'}),
        }
        labels = {
           'title': 'Titulo',
           'content': 'Contenido',
        }

# class BusquedaForm(forms.ModelForm):
#    class Meta:
#       fields = ('title',)

class UsuarioForm(forms.ModelForm):
     class Meta:
        model = Usuario
        fields = '__all__'
        widgets = {                                                        # Me permite utilizar bootstrap para el form
           'nombre': forms.TextInput(attrs={'class':'form-control'}),
           'apellido': forms.TextInput(attrs={'class':'form-control'}),
           'email': forms.TextInput(attrs={'class':'form-control'}),
        }
        labels = {
           'nombre': 'Nombre',
           'apellido': 'Apellido',
           'email': 'Email'
        }

class UsuarioBusquedaForm(forms.Form):
      nombre = forms.CharField(max_length=20, required=False)
      widgets = {                                                        # Me permite utilizar bootstrap para el form
           'nombre': forms.TextInput(attrs={'class':'form-control'}),
        }


class CategoriaForm(forms.ModelForm):
     class Meta:
        model = Categoria
        fields = '__all__'
        widgets = {                                                        # Me permite utilizar bootstrap para el form
           'nombre': forms.TextInput(attrs={'class':'form-control'}),
        }
      #   labels = {
      #      'nombre': 'Nombre',
      #      'apellido': 'Apellido',
      #      'email': 'Email'
      #   }

homepage/views.py
#from django.shortcuts import render
from django.views.generic import TemplateView

class IndexView(TemplateView):
    template_name = 'index.html'

class AboutView(TemplateView):
    template_name = 'about.html'

posts/views.py
from django.shortcuts import render
from .models import Categoria, Post, Usuario
# from .forms import  BusquedaForm
from .forms import  CategoriaForm, PostForm, UsuarioBusquedaForm, UsuarioForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
class PostListView(ListView):
    model = Post
    template_name = 'Posts/post_list.html'

    # def get_queryset(self):
    #     gq = Post.objects.all()
    #     post_a_buscar = self.request.GET.get('filter')  #Revisar porq me devuelve None!
    #     print(post_a_buscar)
    #     if post_a_buscar:
    #         gq = gq.filter(title__icontains=post_a_buscar)
    #     return gq

    # def get(self, request):
    #     title = request.GET.get('title', None)
    #     if title is not None:
    #         posts = Post.objects.filter(title__icontains=title)
    #     else:
    #         posts = Post.objects.all()
    #     return posts
            

class PostDetailView(DetailView):
    model = Post
    template_name = 'Posts/post_detail.html'

class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'Posts/post_form.html'
    success_url = reverse_lazy('post:list')         # Para redirigir al usuario luego de crear un post --> Hace referencia al name que se asigna en posts/urls.py --> NO al nombre del template
    #fields = ('title', 'content')                  # No permite configurar form_class y fields (solo uno)

    def get_context_data(self, **kwargs):
        context = super ().get_context_data(**kwargs)
        context.update({                            # Se añade un nuevo dato de contexto para actualizar vista Form
            'tipo_vista': 'create'
        })
        return context

class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm                           
    success_url = reverse_lazy('post:list')  

    def get_context_data(self, **kwargs):           # Se añade un nuevo dato de contexto para actualizar vista Form
        context = super ().get_context_data(**kwargs)
        context.update({
            'tipo_vista': 'update'
        })
        return context

class PostDeleteView(DeleteView):
    model = Post
    fields = '__all__'
    template_name = 'Posts/post_delete.html'        # DeleteView necesita una ventana de confirmacion para realizar la eliminacion
    success_url = reverse_lazy('post:list')

# ------------------------------------------------------
class UserCreateView(CreateView):
    model = Usuario
    form_class = UsuarioForm
    template_name = 'user_create.html'
    success_url = reverse_lazy('list_users')         


def lista_usuarios(request):    
    nombre_usuario = request.GET.get('nombre', None)
    encontro = False
    if nombre_usuario:
        users = Usuario.objects.filter(nombre__icontains=nombre_usuario)
        encontro = True
    else:
        users = Usuario.objects.all()
        encontro = False
    form = UsuarioBusquedaForm()
    return render(request, "user_list.html", {'form': form, 'users': users, 'encontro': encontro})

# ------------------------------------------------------
class CategoriaCreateView(CreateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'categoria_create.html'
    success_url = reverse_lazy('list_categoria') 

class CategoriaListView(ListView):
    model = Categoria
    template_name = 'categoria_list.html'

templates/Posts/post_delete.html
{% extends 'Posts/post_list.html' %}
{% block title %}
Post delate
{% endblock title %}
{% block body_block%}
<div class="container">
    <h3>¿Esta seguro que quiere eliminar el post: "{{post.title}}"?</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-danger">Eliminar</button>       
        <br>
        <br>
        <a class="btn btn-primary" href="{% url 'post:list'%}"> Salir sin guardar </a>
    </form>
</div>
{%endblock body_block%}

templates/Posts/post_detail.html
{% extends 'Posts/post_list.html' %}
{% block title %}
Post {{post.id}}
{% endblock title %}
{% block body_block%}
<div class="container">
    
    <h2>{{post.title}}</h2>
    <dl>
      <dt>{{post.publish_date}}</dt>
      <dd>{{post.content}}</dd>
    </dl>

    <h4></h4>
    <a class="btn btn-primary" href={% url 'post:update' post.id %}>Modificar Post</a>
    <a class="btn btn-primary" href={% url 'post:delete' post.id %}>Eliminar Post</a>
    <a class="btn btn-primary" href={% url 'post:list' %}>Volver</a>
</div>
{%endblock body_block%}

templates/Posts/post_form.html
{% extends 'Posts/post_list.html' %}

{% block title %}
Post {{tipo_vista}}
{% endblock title %}
{% block body_block%}
<div class="container">
    {% if tipo_vista == "create" %}
        <h2>Crear Post</h2>
    {% else %}
        <h2>Actualizar Post</h2>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <br>
    <a class="btn btn-primary" href="{% url 'post:list'%}"> Salir sin guardar </a>
</div>
{%endblock body_block%}

templates/Posts/post_list.html
{% extends 'index.html' %}


{% block title %}
Posts
{% endblock title %}

{%block navbar_block%}
    <nav class="navbar navbar-expand-lg navbar-dark navbar-shrink" id="mainNav">   
{%endblock navbar_block%}

{% block body_block%}
<div class="container">
    <h2>Listado de posts</h2>
    <br>
    {% comment %} <div class="col-md-3">
        <div class="form-group" >
            <form class="d-flex justify-content-end">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" value={{filter}}> 
                <button class="btn btn-primary" type="submit"><i class="fas fa-search"></i></button>
            </form>
        </div>
    </div> {% endcomment %}

    <table class="table table-striped table-bordered ">
        <thead class="thead-dark">
            <th scope="col">#</th>
            {% comment %} <th scope="col">Usuario</th> {% endcomment %}
            <th scope="col">Titulo</th>
            <th scope="col">Fecha de Creacion</th>
            <th scope="col">Ultima actualizacion</th>
            <th scope="col">Acciones</th>
        </thead>
        <tbody>
            {% if post_list %}
                {% for post in post_list  %}
            <tr>
                <td>{{post.id}}</td>
                {% comment %} <td></td> {% endcomment %}
                <td>{{post.title}}</td>
                <td>{{post.publish_date}}</td>
                <td>{{post.last_update}}</td>
                <td>
                    <a class="btn btn-primary" href="{% url 'post:detail' post.id %}"> Ver detalle </a>
                    <a class="btn btn-primary"  href="{% url 'post:update' post.id %}"> Editar </a>
                    <a class="btn btn-primary"  href="{% url 'post:delete' post.id %}"> Borrar </a>
                </td>
            </tr>
            {% endfor %} 
            {% else %}
            </h2>No hay registro de Posts</h2>
            {% endif %}
        </tbody>
    </table>
</div>

{%endblock body_block%}

{%block js_block%}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script> 
{%endblock js_block%}

templates/about.html
{% extends 'Posts/post_list.html' %}
{% load static %}
{% block title %}
About
{% endblock title %}

{%block navbar_block%}
    <nav class="navbar navbar-expand-lg navbar-dark navbar-shrink" id="mainNav">   
{%endblock navbar_block%}

{% block body_block%}
<section class="page-section bg-light">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Developers</h2>
            <br>
        </div>
        <div class="row">
            <div class="col-lg-7">
                <div class="team-member">
                    <img class="mx-auto rounded-circle" src={%static "assets/img/team/27.jpg"%} alt="..." />
                    <h4>Elmer Estrada</h4>
                    <br>
                    <a class="btn btn-dark btn-social mx-2" href='mailto:elmerestrada27@gmail.com'><i class="fa fa-envelope"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href='https://www.linkedin.com/in/elmerestrada27'><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="team-member">
                    <img class="mx-auto rounded-circle" src={%static "assets/img/team/28.jpeg"%} alt="..." />
                    <h4>Ezequiel Barletta Paz</h4>
                    <br>
                    <a class="btn btn-dark btn-social mx-2" href="mailto:ezequielbarletta@hotmail.com"><i class="fa fa-envelope"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="https://www.linkedin.com/in/ezequielbarlettapaz"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>
{%endblock body_block%}


{%block js_block%}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script> 
{%endblock js_block%}

templates/categoria_create.html
{% extends 'Posts/post_list.html' %}

{% block title %}
Categorias
{% endblock title %}
{% block body_block%}
<div class="container">

    <h2>Crear Categoria</h2>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>

</div>
{%endblock body_block%}

templates/categoria_list.html
{% extends 'Posts/post_list.html' %}

{% block title %}
Categorias
{% endblock title %}
{% block body_block%}

<div class="container">
    <h2>Listado de categorias</h2>
        {% for categoria in object_list %}
            <ul>
                <li><b>{{categoria}}</b> | estado: 
                    {% if  categoria.activo%}
                        activo
                    {% else %}
                        oculto
                    {% endif %}

                </li>
           </ul>
        {% endfor %} 

</div>
{%endblock body_block%}

templates/user_create.html
{% extends 'Posts/post_list.html' %}

{% block title %}
User {{tipo_vista}}
{% endblock title %}
{% block body_block%}
<div class="container">
    <h2>Crear Usuario</h2>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>
{%endblock body_block%}

templates/user_list.html
{% extends 'Posts/post_list.html' %}

{% block title %}
User {{tipo_vista}}
{% endblock title %}
{% block body_block%}
<div class="container">
    <h2>Buscar usuario</h2>
    <form action="" method="get">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <br>
        <button type="submit" class="btn btn-primary">Buscar</button>
    </form>
    <br>
    {% if encontro %}
        <h4>Usuarios encontrados:</h4>
        {% for usuario in users %}
        <li>{{usuario}}</li>
    {% endfor %}
    {% else %}
        <h4>No se busco nada..</h4>
    {% endif %}
    

    

</div>
{%endblock body_block%}